/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AddressInfo;
import model.DemographicInfo;
import model.SavingAccountInfo;
import model.CheckingAccountInfo;
import model.DriverLicenseInfo;
import model.MedicalRecord;

/**
 *
 * @author acer
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    DemographicInfo demographicInfo;
    AddressInfo addressInfo;
    SavingAccountInfo savingAccountInfo;
    CheckingAccountInfo checkingAccountInfo;
    DriverLicenseInfo driverLicenseInfo;
    MedicalRecord medicalRecord;
    public MainJFrame() {
        initComponents();
        demographicInfo = new DemographicInfo();
        addressInfo = new AddressInfo();
        savingAccountInfo = new SavingAccountInfo();
        checkingAccountInfo = new CheckingAccountInfo();
        driverLicenseInfo = new DriverLicenseInfo();
        medicalRecord = new MedicalRecord();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnCreateDemographicInfo = new javax.swing.JButton();
        btnCreateAddressInfo = new javax.swing.JButton();
        btnViewAddressInfo = new javax.swing.JButton();
        btnCreateSavingAccountInformation = new javax.swing.JButton();
        btnViewSavingAccountInformation = new javax.swing.JButton();
        btnViewDemographicInfo4 = new javax.swing.JButton();
        btnCreatCheckingAccountInfo = new javax.swing.JButton();
        btnViewCheckingAccountInfo = new javax.swing.JButton();
        btnCreateDriverLicenseInfo = new javax.swing.JButton();
        btnViewDriverLicenseInfo = new javax.swing.JButton();
        btnCreateMedicalRecord = new javax.swing.JButton();
        btnViewMedicalRecord = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(230);

        btnCreateDemographicInfo.setText("Create Demographic Information");
        btnCreateDemographicInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDemographicInfoActionPerformed(evt);
            }
        });

        btnCreateAddressInfo.setText("Create Address Information");
        btnCreateAddressInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressInfoActionPerformed(evt);
            }
        });

        btnViewAddressInfo.setText("View Address Information");
        btnViewAddressInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddressInfoActionPerformed(evt);
            }
        });

        btnCreateSavingAccountInformation.setText("Create Saving Account Information");
        btnCreateSavingAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavingAccountInformationActionPerformed(evt);
            }
        });

        btnViewSavingAccountInformation.setText("View Saving Account Information");
        btnViewSavingAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavingAccountInformationActionPerformed(evt);
            }
        });

        btnViewDemographicInfo4.setText("View Demographic Information");
        btnViewDemographicInfo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDemographicInfo4ActionPerformed(evt);
            }
        });

        btnCreatCheckingAccountInfo.setText("Create Checking Account Information");
        btnCreatCheckingAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatCheckingAccountInfoActionPerformed(evt);
            }
        });

        btnViewCheckingAccountInfo.setText("View Checking Account Information");
        btnViewCheckingAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingAccountInfoActionPerformed(evt);
            }
        });

        btnCreateDriverLicenseInfo.setText("Create Driver's License Information");
        btnCreateDriverLicenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDriverLicenseInfoActionPerformed(evt);
            }
        });

        btnViewDriverLicenseInfo.setText("View Driver's License Information");
        btnViewDriverLicenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDriverLicenseInfoActionPerformed(evt);
            }
        });

        btnCreateMedicalRecord.setText("Create Medical Record");
        btnCreateMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalRecordActionPerformed(evt);
            }
        });

        btnViewMedicalRecord.setText("View Medical Record");
        btnViewMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalRecordActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatCheckingAccountInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDemographicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateSavingAccountInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnViewSavingAccountInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDemographicInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCheckingAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDriverLicenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDriverLicenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateDemographicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewDemographicInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateSavingAccountInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewSavingAccountInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCreatCheckingAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCheckingAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateDriverLicenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewDriverLicenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDemographicInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDemographicInfoActionPerformed
        // TODO add your handling code here:
        CreateDemographicInfo createDemographicInfo = new CreateDemographicInfo(demographicInfo);
        jSplitPane1.setRightComponent(createDemographicInfo);
        
    }//GEN-LAST:event_btnCreateDemographicInfoActionPerformed

    private void btnCreateAddressInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressInfoActionPerformed
        // TODO add your handling code here:
        CreateAddressInfoPanel createAddressInfoPanel = new CreateAddressInfoPanel(addressInfo);
        jSplitPane1.setRightComponent(createAddressInfoPanel);
        
        
    }//GEN-LAST:event_btnCreateAddressInfoActionPerformed

    private void btnViewAddressInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddressInfoActionPerformed
        // TODO add your handling code here:
        ViewAddressInfoPanel viewAddressInfoPanel = new ViewAddressInfoPanel(addressInfo);
        jSplitPane1.setRightComponent(viewAddressInfoPanel);
    }//GEN-LAST:event_btnViewAddressInfoActionPerformed

    private void btnCreateSavingAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavingAccountInformationActionPerformed
        // TODO add your handling code here:
        CreateSavingAccountInfoPanel createSavingAccountInfoPanel = new CreateSavingAccountInfoPanel(savingAccountInfo);
        jSplitPane1.setRightComponent(createSavingAccountInfoPanel);
    }//GEN-LAST:event_btnCreateSavingAccountInformationActionPerformed

    private void btnViewSavingAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavingAccountInformationActionPerformed
        // TODO add your handling code here:
        ViewSavingAccountInfoPanel viewSavingAccountInfoPanel = new ViewSavingAccountInfoPanel(savingAccountInfo);
        jSplitPane1.setRightComponent(viewSavingAccountInfoPanel);
    }//GEN-LAST:event_btnViewSavingAccountInformationActionPerformed

    private void btnViewDemographicInfo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDemographicInfo4ActionPerformed
        // TODO add your handling code here:
        ViewDemographicInfo viewDemographicInfo = new ViewDemographicInfo(demographicInfo);
        jSplitPane1.setRightComponent(viewDemographicInfo);
    }//GEN-LAST:event_btnViewDemographicInfo4ActionPerformed

    private void btnCreatCheckingAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatCheckingAccountInfoActionPerformed
        // TODO add your handling code here:
        CreateCheckingAccountInfo createCheckingAccountInfo = new CreateCheckingAccountInfo(checkingAccountInfo);
        jSplitPane1.setRightComponent(createCheckingAccountInfo);
    }//GEN-LAST:event_btnCreatCheckingAccountInfoActionPerformed

    private void btnViewCheckingAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingAccountInfoActionPerformed
        // TODO add your handling code here:
        ViewCheckingAccountInfo viewCheckingAccountInfo = new ViewCheckingAccountInfo(checkingAccountInfo);
        jSplitPane1.setRightComponent(viewCheckingAccountInfo);
    }//GEN-LAST:event_btnViewCheckingAccountInfoActionPerformed

    private void btnCreateDriverLicenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDriverLicenseInfoActionPerformed
        // TODO add your handling code here:
        CreateDriverLicenseInfoPanel createDriverLicenseInfoPanel = new CreateDriverLicenseInfoPanel(driverLicenseInfo);
        jSplitPane1.setRightComponent(createDriverLicenseInfoPanel);
    }//GEN-LAST:event_btnCreateDriverLicenseInfoActionPerformed

    private void btnViewDriverLicenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDriverLicenseInfoActionPerformed
        // TODO add your handling code here:
        ViewDriverLicenseInfoPanel viewDriverLicenseInfoPanel = new ViewDriverLicenseInfoPanel(driverLicenseInfo);
        jSplitPane1.setRightComponent(viewDriverLicenseInfoPanel);
    }//GEN-LAST:event_btnViewDriverLicenseInfoActionPerformed

    private void btnCreateMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalRecordActionPerformed
        // TODO add your handling code here:
        CreateMedicalRecord createMedicalRecord = new CreateMedicalRecord( medicalRecord);
        jSplitPane1.setRightComponent(createMedicalRecord);
    }//GEN-LAST:event_btnCreateMedicalRecordActionPerformed

    private void btnViewMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalRecordActionPerformed
        // TODO add your handling code here:
        ViewMedicalRecordPanel viewMedicalRecordPanel = new ViewMedicalRecordPanel(medicalRecord);
        jSplitPane1.setRightComponent(viewMedicalRecordPanel);
    }//GEN-LAST:event_btnViewMedicalRecordActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        ReportPanel reportPanel = new ReportPanel(demographicInfo,addressInfo,savingAccountInfo,checkingAccountInfo,driverLicenseInfo,
                medicalRecord);
        jSplitPane1.setRightComponent(reportPanel);
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatCheckingAccountInfo;
    private javax.swing.JButton btnCreateAddressInfo;
    private javax.swing.JButton btnCreateDemographicInfo;
    private javax.swing.JButton btnCreateDriverLicenseInfo;
    private javax.swing.JButton btnCreateMedicalRecord;
    private javax.swing.JButton btnCreateSavingAccountInformation;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnViewAddressInfo;
    private javax.swing.JButton btnViewCheckingAccountInfo;
    private javax.swing.JButton btnViewDemographicInfo4;
    private javax.swing.JButton btnViewDriverLicenseInfo;
    private javax.swing.JButton btnViewMedicalRecord;
    private javax.swing.JButton btnViewSavingAccountInformation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
